apiVersion: v1
kind: Pod
metadata:
  name: vuln-app
spec:
  containers:
    - name: vuln-app
      image: vuln-app:latest
      securityContext:
        privileged: true
      volumeMounts:
        - name: host-root
          mountPath: /host
  volumes:
    - name: host-root
      hostPath:
        path: /
        type: Directory
